# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=400)),
                ('date', models.DateTimeField()),
                ('speaker', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ON', 'Ongoing'), ('UP', 'Upcoming'), ('PA', 'Past')], default='UP', max_length=2)),
                ('additional_info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
