# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemdeptsite', '0002_auto_20170619_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
