# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemdeptsite', '0003_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Research',
        ),
    ]
