# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chemdeptsite', '0004_delete_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='more_info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
