# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemdeptsite', '0005_news_more_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
    ]
