# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemdeptsite', '0007_headsdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='headsdesk',
            name='name',
            field=models.CharField(default='This is my name', max_length=100),
            preserve_default=False,
        ),
    ]
