# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemdeptsite', '0008_headsdesk_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headsdesk',
            name='profile',
        ),
    ]
