# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 16:25
from __future__ import unicode_literals

import chemdeptsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemdeptsite', '0009_remove_headsdesk_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=chemdeptsite.models.get_image_path)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
