# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtechCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_cirriculum', models.TextField()),
                ('first_semester', models.TextField()),
                ('second_semester', models.TextField()),
                ('third_semester', models.TextField()),
                ('fourth_semester', models.TextField()),
                ('fiveth_semester', models.TextField()),
                ('sixth_semester', models.TextField()),
                ('seventh_semester', models.TextField()),
                ('seventh_department_elective_semester', models.TextField()),
                ('eigth_semester', models.TextField()),
                ('eigth_department_elective_semester', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MscCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_cirriculum', models.TextField()),
                ('first_semester', models.TextField()),
                ('second_semester', models.TextField()),
                ('third_semester', models.TextField()),
                ('fourth_semester', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhdCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermolecular_chemistry', models.TextField()),
                ('new_reagents_for_organic_synthesis', models.TextField()),
                ('spectroscopic_techniques', models.TextField()),
                ('art_in_organic_synthesis', models.TextField()),
                ('bioanalytical_techniques', models.TextField()),
                ('computation_chemistry', models.TextField()),
                ('polymer_science_technology', models.TextField()),
                ('application_glycochemistry', models.TextField()),
            ],
        ),
    ]
