# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btechcourses',
            options={'verbose_name_plural': 'BtechCourses'},
        ),
        migrations.AlterModelOptions(
            name='msccourses',
            options={'verbose_name_plural': 'MscCourses'},
        ),
        migrations.AlterModelOptions(
            name='phdcourses',
            options={'verbose_name_plural': 'PhdCourses'},
        ),
    ]
