# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170714_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btechcourses',
            old_name='fiveth_semester',
            new_name='fifth_semester',
        ),
    ]
