# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170715_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btechcourses',
            old_name='eigth_department_elective_semester',
            new_name='eighth_department_elective_semester',
        ),
        migrations.RenameField(
            model_name='btechcourses',
            old_name='eigth_semester',
            new_name='eighth_semester',
        ),
    ]
