# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170715_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechcourses',
            name='elective_courses_pdf_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msccourses',
            name='new_courses_pdf_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phdcourses',
            name='new_courses_pdf_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
