# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='additional_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
