# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:27
from __future__ import unicode_literals

import PeopleApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0003_faculty_research_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=PeopleApp.models.get_image_path)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PeopleApp.Designations')),
            ],
        ),
    ]
