# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 20:50
from __future__ import unicode_literals

import PeopleApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0008_auto_20170621_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhdStudents',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=PeopleApp.models.get_image_path)),
                ('supervisor', models.CharField(blank=True, max_length=50, null=True)),
                ('research', models.TextField(blank=True, max_length=300, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PeopleApp.Batch')),
            ],
        ),
    ]
