# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0009_phdstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdstudents',
            name='research',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phdstudents',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PeopleApp.Faculty'),
        ),
    ]
