# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0011_auto_20170622_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phdstudents',
            name='id',
        ),
        migrations.AddField(
            model_name='phdstudents',
            name='broadcast_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
