# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:38
from __future__ import unicode_literals

import PeopleApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0012_auto_20170622_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdstudents',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=PeopleApp.models.get_image_path_phd),
        ),
    ]
