# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 07:20
from __future__ import unicode_literals

import PeopleApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0013_auto_20170622_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhdAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emails', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=PeopleApp.models.get_image_path_phd)),
                ('thesis_title', models.TextField(blank=True, max_length=400)),
                ('date_defended', models.DateField(blank=True, null=True)),
                ('phd_supervisor', models.CharField(blank=True, max_length=100)),
                ('phd_supervisor_link', models.CharField(blank=True, default='#', max_length=200)),
                ('current_position', models.TextField(blank=True, max_length=400)),
                ('current_supervisor', models.CharField(blank=True, max_length=100)),
                ('current_supervisor_link', models.CharField(blank=True, default='#', max_length=200)),
                ('extra_info', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
