# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0014_phdalumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdalumni',
            name='thesis_link',
            field=models.TextField(blank=True, default='#', max_length=200),
        ),
    ]
