# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0016_auto_20170623_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='list_position',
            field=models.IntegerField(default=1),
        ),
    ]
