# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0018_auto_20170714_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='teaching',
            field=models.TextField(blank=True, null=True),
        ),
    ]
