# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0019_faculty_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
