# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0021_merge_20170714_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='member_of_professional_bodies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='webpage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
