# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0022_auto_20170714_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='former_research_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phd_students',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
