# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0023_auto_20170715_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='current_research',
            field=models.TextField(blank=True, null=True),
        ),
    ]
