# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0026_auto_20171107_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdalumni',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PeopleApp.Faculty'),
        ),
    ]
