# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20170621_1454'),
        ('PeopleApp', '0027_phdalumni_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Faculty'),
        ),
    ]
