# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0029_remove_faculty_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phdalumni',
            name='phd_supervisor',
        ),
        migrations.RemoveField(
            model_name='phdalumni',
            name='phd_supervisor_link',
        ),
    ]
