# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeopleApp', '0030_auto_20171109_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='phd_students',
        ),
    ]
