# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('principal_investigator', models.CharField(max_length=200)),
                ('sponsoring_agency', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
