# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='principal_investigator',
            field=models.TextField(max_length=200),
        ),
    ]
