# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20170622_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField(max_length=600)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=research.models.get_image_path)),
                ('picture_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Research Areas',
            },
        ),
    ]
