# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_researchareas_object_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchareas',
            name='picture_text',
            field=models.CharField(max_length=500),
        ),
    ]
