# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20170928_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchareas',
            name='detail',
            field=models.TextField(max_length=5000),
        ),
    ]
