# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20170928_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('detail', models.TextField(max_length=5000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=research.models.get_image_path)),
                ('picture_text', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Current Research',
            },
        ),
        migrations.AlterField(
            model_name='researchareas',
            name='picture_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='researchareas',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
