# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name_plural': 'Laboratory & Offices'},
        ),
    ]
